/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package za.co.dharriso.swingy.display;

/**
 *
 * @author devonharrison
 */
public class StartGameForm extends javax.swing.JFrame {

    /**
     * Creates new form StartGameForm
     */
    public StartGameForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        StartGamePanel.setVisible(true);
        CreateHeroPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupOfHeros = new javax.swing.ButtonGroup();
        StartGamePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        newHeroButton = new javax.swing.JButton();
        loadHeroButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();
        CreateHeroPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        wizardRadioButton = new javax.swing.JRadioButton();
        superhumanRadioButton = new javax.swing.JRadioButton();
        interlectRadioButton = new javax.swing.JRadioButton();
        gaurdianRadioButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        heroNameInput = new javax.swing.JTextArea();
        createHeroButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        StartGamePanel.setBackground(new java.awt.Color(36, 37, 42));

        jLabel1.setFont(new java.awt.Font("Gang of Three", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(226, 106, 106));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Just swingy");

        jLabel2.setFont(new java.awt.Font("Gang of Three", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(226, 106, 106));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("- the easiest text based role plating game -");

        newHeroButton.setBackground(new java.awt.Color(56, 57, 62));
        newHeroButton.setFont(new java.awt.Font("Gang of Three", 0, 24)); // NOI18N
        newHeroButton.setForeground(new java.awt.Color(226, 106, 106));
        newHeroButton.setText("new hero");
        newHeroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newHeroButtonMousePressed(evt);
            }
        });
        newHeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newHeroButtonActionPerformed(evt);
            }
        });

        loadHeroButton.setBackground(new java.awt.Color(56, 57, 62));
        loadHeroButton.setFont(new java.awt.Font("Gang of Three", 0, 24)); // NOI18N
        loadHeroButton.setForeground(new java.awt.Color(226, 106, 106));
        loadHeroButton.setText("load hero");

        aboutButton.setBackground(new java.awt.Color(56, 57, 62));
        aboutButton.setFont(new java.awt.Font("Gang of Three", 0, 24)); // NOI18N
        aboutButton.setForeground(new java.awt.Color(226, 106, 106));
        aboutButton.setText("About");

        javax.swing.GroupLayout StartGamePanelLayout = new javax.swing.GroupLayout(StartGamePanel);
        StartGamePanel.setLayout(StartGamePanelLayout);
        StartGamePanelLayout.setHorizontalGroup(
            StartGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StartGamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StartGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newHeroButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loadHeroButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aboutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        StartGamePanelLayout.setVerticalGroup(
            StartGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartGamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(newHeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(loadHeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(aboutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        CreateHeroPanel.setBackground(new java.awt.Color(36, 37, 42));

        jLabel3.setFont(new java.awt.Font("Gang of Three", 0, 46)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(226, 106, 106));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Create new hero");

        jLabel4.setFont(new java.awt.Font("Gang of Three", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(226, 106, 106));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Please select the type of hero");

        buttonGroupOfHeros.add(wizardRadioButton);
        wizardRadioButton.setFont(new java.awt.Font("Gang of Three", 0, 12)); // NOI18N
        wizardRadioButton.setForeground(new java.awt.Color(226, 106, 106));
        wizardRadioButton.setText("Wizard");
        wizardRadioButton.setContentAreaFilled(false);

        buttonGroupOfHeros.add(superhumanRadioButton);
        superhumanRadioButton.setFont(new java.awt.Font("Gang of Three", 0, 12)); // NOI18N
        superhumanRadioButton.setForeground(new java.awt.Color(226, 106, 106));
        superhumanRadioButton.setText("superhuman");
        superhumanRadioButton.setContentAreaFilled(false);

        buttonGroupOfHeros.add(interlectRadioButton);
        interlectRadioButton.setFont(new java.awt.Font("Gang of Three", 0, 12)); // NOI18N
        interlectRadioButton.setForeground(new java.awt.Color(226, 106, 106));
        interlectRadioButton.setText("interlect");

        buttonGroupOfHeros.add(gaurdianRadioButton);
        gaurdianRadioButton.setFont(new java.awt.Font("Gang of Three", 0, 12)); // NOI18N
        gaurdianRadioButton.setForeground(new java.awt.Color(226, 106, 106));
        gaurdianRadioButton.setText("gaurdian");
        gaurdianRadioButton.setContentAreaFilled(false);

        jLabel5.setFont(new java.awt.Font("Gang of Three", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(226, 106, 106));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Give your hero a name");

        heroNameInput.setBackground(new java.awt.Color(56, 57, 62));
        heroNameInput.setColumns(20);
        heroNameInput.setFont(new java.awt.Font("Gang of Three", 0, 24)); // NOI18N
        heroNameInput.setForeground(new java.awt.Color(226, 106, 106));
        heroNameInput.setRows(5);
        jScrollPane1.setViewportView(heroNameInput);

        createHeroButton.setFont(new java.awt.Font("Gang of Three", 0, 24)); // NOI18N
        createHeroButton.setForeground(new java.awt.Color(226, 106, 106));
        createHeroButton.setText("Create hero");

        javax.swing.GroupLayout CreateHeroPanelLayout = new javax.swing.GroupLayout(CreateHeroPanel);
        CreateHeroPanel.setLayout(CreateHeroPanelLayout);
        CreateHeroPanelLayout.setHorizontalGroup(
            CreateHeroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateHeroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CreateHeroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createHeroButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(CreateHeroPanelLayout.createSequentialGroup()
                        .addGroup(CreateHeroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(interlectRadioButton)
                            .addComponent(superhumanRadioButton)
                            .addComponent(gaurdianRadioButton)
                            .addComponent(wizardRadioButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CreateHeroPanelLayout.setVerticalGroup(
            CreateHeroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateHeroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wizardRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gaurdianRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(interlectRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(superhumanRadioButton)
                .addGap(31, 31, 31)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(createHeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StartGamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(CreateHeroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StartGamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(CreateHeroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newHeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newHeroButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newHeroButtonActionPerformed

    private void newHeroButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newHeroButtonMousePressed
        // TODO add your handling code here:
        StartGamePanel.setVisible(false);
        CreateHeroPanel.setVisible(true);
    }//GEN-LAST:event_newHeroButtonMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreateHeroPanel;
    private javax.swing.JPanel StartGamePanel;
    private javax.swing.JButton aboutButton;
    private javax.swing.ButtonGroup buttonGroupOfHeros;
    private javax.swing.JButton createHeroButton;
    private javax.swing.JRadioButton gaurdianRadioButton;
    private javax.swing.JTextArea heroNameInput;
    private javax.swing.JRadioButton interlectRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadHeroButton;
    private javax.swing.JButton newHeroButton;
    private javax.swing.JRadioButton superhumanRadioButton;
    private javax.swing.JRadioButton wizardRadioButton;
    // End of variables declaration//GEN-END:variables
}
