/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package za.co.dharriso.swingy.views;

import java.util.concurrent.ThreadLocalRandom;

import javax.swing.JOptionPane;

import za.co.dharriso.swingy.hero.Hero;
import za.co.dharriso.swingy.hero.Legion;
import za.co.dharriso.swingy.world.Map;

/**
 *
 * @author devonharrison
 */
public class GamePlayForm extends javax.swing.JFrame {

    /**
     * Creates new form GamePlayForm
     */


    public GamePlayForm() {
        initComponents();
        startGamePanel.setVisible(true);
        createHeroPanel.setVisible(false);
        decideToFightPanel.setVisible(false);
        dropPanel.setVisible(false);
        loadHeroPanel.setVisible(false);
        navigateMapPanel.setVisible(false);
        noDropPanel.setVisible(false);
        heroCreatedPanel.setVisible(false);
        viewStatsPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heroTypeButtonGroup = new javax.swing.ButtonGroup();
        startGamePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        aboutButton = new javax.swing.JButton();
        loadHeroButton = new javax.swing.JButton();
        newHeroButton = new javax.swing.JButton();
        navigateMapPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        northButton = new javax.swing.JButton();
        eastButton = new javax.swing.JButton();
        southButton = new javax.swing.JButton();
        westButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        createHeroPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        wizardRadioButton = new javax.swing.JRadioButton();
        gaurdianRadioButton = new javax.swing.JRadioButton();
        interlectRadioButton = new javax.swing.JRadioButton();
        superhumanRadioButton = new javax.swing.JRadioButton();
        heroNameTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        createHeroButton = new javax.swing.JButton();
        loadHeroPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        noDropPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        onforthButton = new javax.swing.JButton();
        decideToFightPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        fightButton = new javax.swing.JButton();
        runButton = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        dropPanel = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        pickupButton = new javax.swing.JButton();
        nahButton = new javax.swing.JButton();
        heroCreatedPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        continueButton = new javax.swing.JButton();
        displayHeroNameLabel = new javax.swing.JLabel();
        displayHeroTypeLabel = new javax.swing.JLabel();
        displayHeroAttackLabel = new javax.swing.JLabel();
        displayHeroDefenseLabel = new javax.swing.JLabel();
        displayHeroLevelLabel = new javax.swing.JLabel();
        displayHeroXpLabel1 = new javax.swing.JLabel();
        winPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        losePanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        viewStatsPanel = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        viewStatsButton = new javax.swing.JButton();
        noViewStatsButton = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        startGamePanel.setBackground(new java.awt.Color(36, 37, 42));

        jLabel1.setFont(new java.awt.Font("Gang of Three", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(226, 106, 106));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Just swingy");

        jLabel2.setFont(new java.awt.Font("Gang of Three", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(226, 106, 106));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("- the easiest text based role playing game -");

        aboutButton.setFont(new java.awt.Font("Gang of Three", 0, 24)); // NOI18N
        aboutButton.setForeground(new java.awt.Color(226, 106, 106));
        aboutButton.setText("about");
        aboutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aboutButtonMousePressed(evt);
            }
        });

        loadHeroButton.setFont(new java.awt.Font("Gang of Three", 0, 24)); // NOI18N
        loadHeroButton.setForeground(new java.awt.Color(226, 106, 106));
        loadHeroButton.setText("load hero");
        loadHeroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loadHeroButtonMousePressed(evt);
            }
        });

        newHeroButton.setFont(new java.awt.Font("Gang of Three", 0, 24)); // NOI18N
        newHeroButton.setForeground(new java.awt.Color(226, 106, 106));
        newHeroButton.setText("new hero");
        newHeroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newHeroButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout startGamePanelLayout = new javax.swing.GroupLayout(startGamePanel);
        startGamePanel.setLayout(startGamePanelLayout);
        startGamePanelLayout.setHorizontalGroup(
            startGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startGamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(startGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aboutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(loadHeroButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newHeroButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        startGamePanelLayout.setVerticalGroup(
            startGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startGamePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(newHeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(loadHeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(aboutButton)
                .addGap(62, 62, 62))
        );

        navigateMapPanel.setBackground(new java.awt.Color(36, 37, 42));

        jLabel3.setFont(new java.awt.Font("Gang of Three", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(226, 106, 106));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Just swingy");

        jLabel13.setFont(new java.awt.Font("Gang of Three", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(226, 106, 106));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("- time to explore -");

        northButton.setFont(new java.awt.Font("Gang of Three", 0, 24)); // NOI18N
        northButton.setForeground(new java.awt.Color(226, 106, 106));
        northButton.setText("north");
        northButton.setToolTipText("");
        northButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                northButtonMousePressed(evt);
            }
        });

        eastButton.setFont(new java.awt.Font("Gang of Three", 0, 24)); // NOI18N
        eastButton.setForeground(new java.awt.Color(226, 106, 106));
        eastButton.setText("east");
        eastButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eastButtonMousePressed(evt);
            }
        });

        southButton.setFont(new java.awt.Font("Gang of Three", 0, 24)); // NOI18N
        southButton.setForeground(new java.awt.Color(226, 106, 106));
        southButton.setText("south");
        southButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                southButtonMousePressed(evt);
            }
        });

        westButton.setFont(new java.awt.Font("Gang of Three", 0, 24)); // NOI18N
        westButton.setForeground(new java.awt.Color(226, 106, 106));
        westButton.setText("west");
        westButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                westButtonMousePressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Gang of Three", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(226, 106, 106));
        jLabel14.setText("Select a direction to walk in");

        javax.swing.GroupLayout navigateMapPanelLayout = new javax.swing.GroupLayout(navigateMapPanel);
        navigateMapPanel.setLayout(navigateMapPanelLayout);
        navigateMapPanelLayout.setHorizontalGroup(
            navigateMapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigateMapPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navigateMapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(northButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(westButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(southButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eastButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        navigateMapPanelLayout.setVerticalGroup(
            navigateMapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigateMapPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(northButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(eastButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(southButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(westButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        createHeroPanel.setBackground(new java.awt.Color(36, 37, 42));

        jLabel4.setFont(new java.awt.Font("Gang of Three", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(226, 106, 106));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Just swingy");

        jLabel10.setFont(new java.awt.Font("Gang of Three", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(226, 106, 106));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("- Create new hero -");

        wizardRadioButton.setBackground(new java.awt.Color(36, 37, 42));
        heroTypeButtonGroup.add(wizardRadioButton);
        wizardRadioButton.setFont(new java.awt.Font("Gang of Three", 0, 16)); // NOI18N
        wizardRadioButton.setForeground(new java.awt.Color(226, 106, 106));
        wizardRadioButton.setText("wizard");

        gaurdianRadioButton.setBackground(new java.awt.Color(36, 37, 42));
        heroTypeButtonGroup.add(gaurdianRadioButton);
        gaurdianRadioButton.setFont(new java.awt.Font("Gang of Three", 0, 16)); // NOI18N
        gaurdianRadioButton.setForeground(new java.awt.Color(226, 106, 106));
        gaurdianRadioButton.setText("gaurdian");

        interlectRadioButton.setBackground(new java.awt.Color(36, 37, 42));
        heroTypeButtonGroup.add(interlectRadioButton);
        interlectRadioButton.setFont(new java.awt.Font("Gang of Three", 0, 16)); // NOI18N
        interlectRadioButton.setForeground(new java.awt.Color(226, 106, 106));
        interlectRadioButton.setText("interlect");

        superhumanRadioButton.setBackground(new java.awt.Color(36, 37, 42));
        heroTypeButtonGroup.add(superhumanRadioButton);
        superhumanRadioButton.setFont(new java.awt.Font("Gang of Three", 0, 16)); // NOI18N
        superhumanRadioButton.setForeground(new java.awt.Color(226, 106, 106));
        superhumanRadioButton.setText("superhuman");

        heroNameTextField.setBackground(new java.awt.Color(36, 37, 42));
        heroNameTextField.setFont(new java.awt.Font("Gang of Three", 0, 16)); // NOI18N
        heroNameTextField.setForeground(new java.awt.Color(226, 106, 106));

        jLabel11.setFont(new java.awt.Font("Gang of Three", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(226, 106, 106));
        jLabel11.setText("Select hero type");

        jLabel12.setFont(new java.awt.Font("Gang of Three", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(226, 106, 106));
        jLabel12.setText("Give your hero a name");

        createHeroButton.setFont(new java.awt.Font("Gang of Three", 0, 24)); // NOI18N
        createHeroButton.setForeground(new java.awt.Color(226, 106, 106));
        createHeroButton.setText("create hero");
        createHeroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                createHeroButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout createHeroPanelLayout = new javax.swing.GroupLayout(createHeroPanel);
        createHeroPanel.setLayout(createHeroPanelLayout);
        createHeroPanelLayout.setHorizontalGroup(
            createHeroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createHeroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createHeroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(heroNameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addGroup(createHeroPanelLayout.createSequentialGroup()
                        .addGroup(createHeroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(superhumanRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gaurdianRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wizardRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(interlectRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(createHeroButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        createHeroPanelLayout.setVerticalGroup(
            createHeroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createHeroPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wizardRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gaurdianRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(superhumanRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(interlectRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(heroNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(createHeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        loadHeroPanel.setBackground(new java.awt.Color(36, 37, 42));

        jLabel5.setFont(new java.awt.Font("Gang of Three", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(226, 106, 106));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Just swingy");

        jLabel24.setFont(new java.awt.Font("Gang of Three", 0, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(226, 106, 106));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("- load hero -");

        javax.swing.GroupLayout loadHeroPanelLayout = new javax.swing.GroupLayout(loadHeroPanel);
        loadHeroPanel.setLayout(loadHeroPanelLayout);
        loadHeroPanelLayout.setHorizontalGroup(
            loadHeroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadHeroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loadHeroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                .addContainerGap())
        );
        loadHeroPanelLayout.setVerticalGroup(
            loadHeroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadHeroPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(419, Short.MAX_VALUE))
        );

        noDropPanel.setBackground(new java.awt.Color(36, 37, 42));

        jLabel7.setFont(new java.awt.Font("Gang of Three", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(226, 106, 106));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Just swingy");

        jLabel21.setFont(new java.awt.Font("Gang of Three", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(226, 106, 106));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("- on todays episode of \"was that a waste of time\" -");

        onforthButton.setFont(new java.awt.Font("Gang of Three", 0, 24)); // NOI18N
        onforthButton.setForeground(new java.awt.Color(226, 106, 106));
        onforthButton.setText("onforth");

        javax.swing.GroupLayout noDropPanelLayout = new javax.swing.GroupLayout(noDropPanel);
        noDropPanel.setLayout(noDropPanelLayout);
        noDropPanelLayout.setHorizontalGroup(
            noDropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, noDropPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(noDropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(onforthButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        noDropPanelLayout.setVerticalGroup(
            noDropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noDropPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addComponent(onforthButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        decideToFightPanel.setBackground(new java.awt.Color(36, 37, 42));

        jLabel16.setFont(new java.awt.Font("Gang of Three", 0, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(226, 106, 106));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Just swingy");

        jLabel17.setFont(new java.awt.Font("Gang of Three", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(226, 106, 106));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("- aggresive boi  found -");

        jLabel19.setFont(new java.awt.Font("Gang of Three", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(226, 106, 106));
        jLabel19.setText("Seems we've encounted an aggresive boi,");

        jLabel18.setFont(new java.awt.Font("Gang of Three", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(226, 106, 106));
        jLabel18.setText("do we want to fight him or nah?");
        jLabel18.setToolTipText("");

        fightButton.setFont(new java.awt.Font("Gang of Three", 0, 18)); // NOI18N
        fightButton.setForeground(new java.awt.Color(226, 106, 106));
        fightButton.setText("fight fight fight!");
        fightButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fightButtonMousePressed(evt);
            }
        });

        runButton.setFont(new java.awt.Font("Gang of Three", 0, 18)); // NOI18N
        runButton.setForeground(new java.awt.Color(226, 106, 106));
        runButton.setText("run!");
        runButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                runButtonMousePressed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Gang of Three", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(226, 106, 106));
        jLabel20.setText("if we fight him, he might drop some loot!");
        jLabel20.setToolTipText("");

        javax.swing.GroupLayout decideToFightPanelLayout = new javax.swing.GroupLayout(decideToFightPanel);
        decideToFightPanel.setLayout(decideToFightPanelLayout);
        decideToFightPanelLayout.setHorizontalGroup(
            decideToFightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decideToFightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(decideToFightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(runButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        decideToFightPanelLayout.setVerticalGroup(
            decideToFightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decideToFightPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(fightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(runButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        dropPanel.setBackground(new java.awt.Color(36, 37, 42));

        jLabel22.setFont(new java.awt.Font("Gang of Three", 0, 48)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(226, 106, 106));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Just swingy");

        jLabel23.setFont(new java.awt.Font("Gang of Three", 0, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(226, 106, 106));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("- Risked it and got the biscuit -");

        pickupButton.setFont(new java.awt.Font("Gang of Three", 0, 24)); // NOI18N
        pickupButton.setForeground(new java.awt.Color(226, 106, 106));
        pickupButton.setText("pickup");
        pickupButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pickupButtonMousePressed(evt);
            }
        });

        nahButton.setFont(new java.awt.Font("Gang of Three", 0, 24)); // NOI18N
        nahButton.setForeground(new java.awt.Color(226, 106, 106));
        nahButton.setText("nah");

        javax.swing.GroupLayout dropPanelLayout = new javax.swing.GroupLayout(dropPanel);
        dropPanel.setLayout(dropPanelLayout);
        dropPanelLayout.setHorizontalGroup(
            dropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dropPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pickupButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(nahButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        dropPanelLayout.setVerticalGroup(
            dropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dropPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(pickupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(nahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        heroCreatedPanel.setBackground(new java.awt.Color(36, 37, 42));
        heroCreatedPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                heroCreatedPanelMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Gang of Three", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(226, 106, 106));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Just swingy");

        jLabel15.setFont(new java.awt.Font("Gang of Three", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(226, 106, 106));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("- Hero stats -");

        continueButton.setFont(new java.awt.Font("Gang of Three", 0, 24)); // NOI18N
        continueButton.setForeground(new java.awt.Color(226, 106, 106));
        continueButton.setText("continue");
        continueButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                continueButtonMousePressed(evt);
            }
        });
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        displayHeroNameLabel.setFont(new java.awt.Font("Gang of Three", 0, 18)); // NOI18N
        displayHeroNameLabel.setForeground(new java.awt.Color(226, 106, 106));

        displayHeroTypeLabel.setFont(new java.awt.Font("Gang of Three", 0, 18)); // NOI18N
        displayHeroTypeLabel.setForeground(new java.awt.Color(226, 106, 106));

        displayHeroAttackLabel.setFont(new java.awt.Font("Gang of Three", 0, 18)); // NOI18N
        displayHeroAttackLabel.setForeground(new java.awt.Color(226, 106, 106));

        displayHeroDefenseLabel.setFont(new java.awt.Font("Gang of Three", 0, 18)); // NOI18N
        displayHeroDefenseLabel.setForeground(new java.awt.Color(226, 106, 106));

        displayHeroLevelLabel.setFont(new java.awt.Font("Gang of Three", 0, 18)); // NOI18N
        displayHeroLevelLabel.setForeground(new java.awt.Color(226, 106, 106));

        displayHeroXpLabel1.setFont(new java.awt.Font("Gang of Three", 0, 18)); // NOI18N
        displayHeroXpLabel1.setForeground(new java.awt.Color(226, 106, 106));

        javax.swing.GroupLayout heroCreatedPanelLayout = new javax.swing.GroupLayout(heroCreatedPanel);
        heroCreatedPanel.setLayout(heroCreatedPanelLayout);
        heroCreatedPanelLayout.setHorizontalGroup(
            heroCreatedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(heroCreatedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(heroCreatedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayHeroNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(continueButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayHeroTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayHeroAttackLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayHeroDefenseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayHeroLevelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayHeroXpLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        heroCreatedPanelLayout.setVerticalGroup(
            heroCreatedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(heroCreatedPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayHeroNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayHeroTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayHeroAttackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayHeroDefenseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayHeroLevelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayHeroXpLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(continueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        winPanel.setBackground(new java.awt.Color(36, 37, 42));

        jLabel8.setFont(new java.awt.Font("Gang of Three", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(226, 106, 106));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Just swingy");

        jLabel25.setFont(new java.awt.Font("Gang of Three", 0, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(226, 106, 106));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("- YOU WON -");

        javax.swing.GroupLayout winPanelLayout = new javax.swing.GroupLayout(winPanel);
        winPanel.setLayout(winPanelLayout);
        winPanelLayout.setHorizontalGroup(
            winPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, winPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        winPanelLayout.setVerticalGroup(
            winPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(419, Short.MAX_VALUE))
        );

        losePanel.setBackground(new java.awt.Color(36, 37, 42));

        jLabel9.setFont(new java.awt.Font("Gang of Three", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(226, 106, 106));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Just swingy");

        jLabel26.setFont(new java.awt.Font("Gang of Three", 0, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(226, 106, 106));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("- YOU LOST -");

        javax.swing.GroupLayout losePanelLayout = new javax.swing.GroupLayout(losePanel);
        losePanel.setLayout(losePanelLayout);
        losePanelLayout.setHorizontalGroup(
            losePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, losePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        losePanelLayout.setVerticalGroup(
            losePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(losePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(419, Short.MAX_VALUE))
        );

        viewStatsPanel.setBackground(new java.awt.Color(36, 37, 42));

        jLabel27.setFont(new java.awt.Font("Gang of Three", 0, 48)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(226, 106, 106));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Just swingy");

        jLabel28.setFont(new java.awt.Font("Gang of Three", 0, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(226, 106, 106));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("- prepare for battle -");

        viewStatsButton.setFont(new java.awt.Font("Gang of Three", 0, 18)); // NOI18N
        viewStatsButton.setForeground(new java.awt.Color(226, 106, 106));
        viewStatsButton.setText("view stats");
        viewStatsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                viewStatsButtonMousePressed(evt);
            }
        });

        noViewStatsButton.setFont(new java.awt.Font("Gang of Three", 0, 18)); // NOI18N
        noViewStatsButton.setForeground(new java.awt.Color(226, 106, 106));
        noViewStatsButton.setText("I know what I'm capable of");
        noViewStatsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                noViewStatsButtonMousePressed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Gang of Three", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(226, 106, 106));
        jLabel31.setText("Would you like to view our strength?");
        jLabel31.setToolTipText("");

        javax.swing.GroupLayout viewStatsPanelLayout = new javax.swing.GroupLayout(viewStatsPanel);
        viewStatsPanel.setLayout(viewStatsPanelLayout);
        viewStatsPanelLayout.setHorizontalGroup(
            viewStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewStatsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noViewStatsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewStatsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        viewStatsPanelLayout.setVerticalGroup(
            viewStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewStatsPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(viewStatsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(noViewStatsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startGamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(navigateMapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(createHeroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(loadHeroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(noDropPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(decideToFightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(dropPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(heroCreatedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(winPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(losePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(viewStatsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(2, 2, 2)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startGamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(navigateMapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 24, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(createHeroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(loadHeroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(noDropPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(decideToFightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(dropPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(heroCreatedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(winPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(losePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(viewStatsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(2, 2, 2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newHeroButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newHeroButtonMousePressed
        startGamePanel.setVisible(false);
        createHeroPanel.setVisible(true);
    }//GEN-LAST:event_newHeroButtonMousePressed

    private void aboutButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutButtonMousePressed

    private void loadHeroButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadHeroButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadHeroButtonMousePressed

    private void northButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_northButtonMousePressed
        this.run = this.hero.updatePostion("north");
        if (this.run == 1){
            winPanel.setVisible(true);
            navigateMapPanel.setVisible(false);
        }
        else{
            if (this.hero.checkPosition("north") == 1){
                decideToFightPanel.setVisible(true);
                navigateMapPanel.setVisible(false);
            }
        }
    }//GEN-LAST:event_northButtonMousePressed

    private void eastButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eastButtonMousePressed
        this.run = this.hero.updatePostion("east");
        if (this.run == 1){
            winPanel.setVisible(true);
            navigateMapPanel.setVisible(false);
        }
        else{
            if (this.hero.checkPosition("east") == 1){
                decideToFightPanel.setVisible(true);
                navigateMapPanel.setVisible(false);
            }
        }
    }//GEN-LAST:event_eastButtonMousePressed

    private void southButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_southButtonMousePressed
        this.run = this.hero.updatePostion("south");
        if (this.run == 1){
            winPanel.setVisible(true);
            navigateMapPanel.setVisible(false);
        }
        else{
            if (this.hero.checkPosition("south") == 1){
                decideToFightPanel.setVisible(true);
                navigateMapPanel.setVisible(false);
            }
        }
    }//GEN-LAST:event_southButtonMousePressed

    private void westButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_westButtonMousePressed
        this.run = this.hero.updatePostion("west");
        if (this.run == 1){
            winPanel.setVisible(true);
            navigateMapPanel.setVisible(false);
        }
        else{
            if (this.hero.checkPosition("west") == 1){
                decideToFightPanel.setVisible(true);
                navigateMapPanel.setVisible(false);
            }
        }
    }//GEN-LAST:event_westButtonMousePressed

    private void createHeroButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createHeroButtonMousePressed
        String heroName = heroNameTextField.getText();
        Map m = new Map(1);
        String heroType = "";
        if(heroName.length() > 0){
            if (wizardRadioButton.isSelected() == true){
                heroType = "wizard";
            }
            else if(interlectRadioButton.isSelected() == true){
                heroType = "interlect";
            }
            else if(superhumanRadioButton.isSelected() == true){
                heroType = "superhuman";
            }
            else if(gaurdianRadioButton.isSelected() == true){
                heroType = "guardian";
            }
            else{
                JOptionPane.showMessageDialog(null, "No hero type selected", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "No hero name given", "Error", JOptionPane.ERROR_MESSAGE);
        }

        if (heroType.length() > 0 && heroName.length() > 0){
            try{
                this.hero = new Legion().newHero(heroName, heroType, 5, 5, m);
                setHeroStatsLabel(heroName, heroType);
                heroCreatedPanel.setVisible(true);
                createHeroPanel.setVisible(false);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error creating hero: " + e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_createHeroButtonMousePressed

    private void fightButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fightButtonMousePressed
        int villain = ThreadLocalRandom.current().nextInt(2, 10);
        String result = hero.fight(villain);
        if (result.equals("lose")){
            losePanel.setVisible(true);
            decideToFightPanel.setVisible(false);
        }
        else{
            dropPanel.setVisible(true);
            decideToFightPanel.setVisible(false);
        }
    }//GEN-LAST:event_fightButtonMousePressed

    private void runButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_runButtonMousePressed
        decideToFightPanel.setVisible(false);
        navigateMapPanel.setVisible(true);
    }//GEN-LAST:event_runButtonMousePressed

    private void continueButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continueButtonMousePressed
        heroCreatedPanel.setVisible(false);
        navigateMapPanel.setVisible(true);
    }//GEN-LAST:event_continueButtonMousePressed

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_continueButtonActionPerformed

    private void heroCreatedPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heroCreatedPanelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_heroCreatedPanelMousePressed

    private void viewStatsButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewStatsButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewStatsButtonMousePressed

    private void noViewStatsButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noViewStatsButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_noViewStatsButtonMousePressed

    private void pickupButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noViewStatsButtonMousePressed
        String [] arr = {"weapon", "armour", "helm"};
        int artifact = ThreadLocalRandom.current().nextInt(0, 3);
        hero.heroStatsChange(arr[artifact]);
        dropPanel.setVisible(false);
        navigateMapPanel.setVisible(true);
    }//GEN-LAST:event_noViewStatsButtonMousePressed

    private void setHeroStatsLabel(String name, String type){
        int attack = 0;
        int defense = 0;
        int level = 1;
        int xp = 0;

        switch(type){
            case "guardian":
                attack = 60;
                defense = 20;
                break;
            case "interlect":
                attack = 30;
                defense = 50;
                break;
            case "superhuman":
                attack = 90;
                defense = 90;
                break;
            case "wizard":
                attack = 100;
                defense = 100;
                break;
        }
        
        displayHeroNameLabel.setText("Name: " + name);
        displayHeroTypeLabel.setText("Type: " + type);
        displayHeroAttackLabel.setText("Attack: " + Integer.toString(attack));
        displayHeroDefenseLabel.setText("Defense: " + Integer.toString(defense));
        displayHeroLevelLabel.setText("Level: " + Integer.toString(level));
        displayHeroXpLabel1.setText("Experience: " + Integer.toString(xp));
    }
    /**
     * @param args the command line arguments
     */


    private Hero hero;
    private int run;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutButton;
    private javax.swing.JButton continueButton;
    private javax.swing.JButton createHeroButton;
    private javax.swing.JPanel createHeroPanel;
    private javax.swing.JPanel decideToFightPanel;
    private javax.swing.JLabel displayHeroAttackLabel;
    private javax.swing.JLabel displayHeroDefenseLabel;
    private javax.swing.JLabel displayHeroLevelLabel;
    private javax.swing.JLabel displayHeroNameLabel;
    private javax.swing.JLabel displayHeroTypeLabel;
    private javax.swing.JLabel displayHeroXpLabel1;
    private javax.swing.JPanel dropPanel;
    private javax.swing.JButton eastButton;
    private javax.swing.JButton fightButton;
    private javax.swing.JRadioButton gaurdianRadioButton;
    private javax.swing.JPanel heroCreatedPanel;
    private javax.swing.JTextField heroNameTextField;
    private javax.swing.ButtonGroup heroTypeButtonGroup;
    private javax.swing.JRadioButton interlectRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton loadHeroButton;
    private javax.swing.JPanel loadHeroPanel;
    private javax.swing.JPanel losePanel;
    private javax.swing.JButton nahButton;
    private javax.swing.JPanel navigateMapPanel;
    private javax.swing.JButton newHeroButton;
    private javax.swing.JPanel noDropPanel;
    private javax.swing.JButton noViewStatsButton;
    private javax.swing.JButton northButton;
    private javax.swing.JButton onforthButton;
    private javax.swing.JButton pickupButton;
    private javax.swing.JButton runButton;
    private javax.swing.JButton southButton;
    private javax.swing.JPanel startGamePanel;
    private javax.swing.JRadioButton superhumanRadioButton;
    private javax.swing.JButton viewStatsButton;
    private javax.swing.JPanel viewStatsPanel;
    private javax.swing.JButton westButton;
    private javax.swing.JPanel winPanel;
    private javax.swing.JRadioButton wizardRadioButton;
    // End of variables declaration//GEN-END:variables
}
